### ISSUE TITLE
Ability to Search Movies

### ISSUE THREAD

**Issue by sschipke-conga** [sschipke-conga/black-stories-fe#31]
As a user, I should be able to search for a specific move (title only) when viewing a list of movies

**Comment by grchappell** [comment]
@sschipke-conga When you click the search icon, can the text field automatically be live? Right now, you have to click the word search, then click in the search bar. 

On desktop, If you click search on one page, the bar pops us, but if you navigate to another page, it doesn't go away. Can it go away?

On mobile, when you click search, the bar pops up, let's consider getting rid of the word search once the bar pops up. I naturally clicked the word search instead of the magnifying glass, I wonder if others will too

**Comment by grchappell** [comment]
@sschipke-conga for the previously watched movies, what do you think of having the date watched on each movie's page? This solves the issue of them coming up when searched (which I'm here for)

<img width="1280" alt="Screen Shot 2021-03-14 at 8 47 35 PM" src="https://user-images.githubusercontent.com/23510918/111097410-11831280-8507-11eb-87b9-1af32ed0b687.png">
